version: '3.9'

services:
  app:
    container_name: vitepress
    build: .
    ports:
      - 127.0.0.1:3003:5000
    environment:
      LETSENCRYPT_HOST: www.zwd.xyz
      VIRTUAL_HOST: www.zwd.xyz
      VIRTUAL_PORT: 3003
      VIRTUAL_PATH: /fe-stack
    command: yarn docs:serve
    networks:
      - blog

networks:
  blog:
    external:
      name: blog
