version: '3.9'

services:
  app:
    container_name: vitepress
    build: .
    ports:
      - 5000:5000
    environment:
      LETSENCRYPT_HOST: www.zwd.xyz
      VIRTUAL_HOST: www.zwd.xyz
      VIRTUAL_PORT: 5000
      VIRTUAL_PATH: /fe-stack
    command: yarn docs:serve
    networks:
      - blog

networks:
  blog:
    external:
      name: blog
